### ISSUE TITLE
Any way to get the full error details in the response?

### ISSUE THREAD

**Issue by rw3iss** [Tjatse/req-fast#10]
Upon an error the callback error argument just contains the status code and a standard response.
Is there anyway to get other details like the response headers and everything else?

**Comment by Tjatse** [comment]
Just try `npm i req-fast@0.2.16`
and handle `error` and `response` by
```javascript
(err, response) => {
  if (err) {
    console.error(err.toString())
  }
  if (response) {
    // you can access response now
  }
}
```
