### ISSUE TITLE
toString() failed 

### ISSUE THREAD

**Issue by sladg** [Tjatse/req-fast#15]
This is error I got:

> buffer.js:503
>     throw new Error('"toString()" failed');
>     ^
> 
> Error: "toString()" failed
>     at Buffer.toString (buffer.js:503:11)
>     at RequestStream.<anonymous> (/home/adminvm/crawler/custom_modules/req-fast/lib/req.js:91:29)
>     at emitNone (events.js:86:13)
>     at RequestStream.emit (events.js:188:7)
>     at RequestStream.onEnd (/home/adminvm/crawler/custom_modules/req-fast/lib/req_stream.js:241:10)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:188:7)
>     at endReadableNT (_stream_readable.js:975:12)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

According to this thread: [https://github.com/nodejs/node/issues/3175](url)
This occurs when buffer exceed maximal length (268435440). 

Code responsible: 
/lib/req.js (line:91)
```
    if (typeof resp.body !== 'string') {
      resp.body = resp.body.toString()
    }
```

So I would recommend putting some function, which divides code to smaller parts and after .toString(), it puts them together.

I fixed it by simple: 
```
if (resp.body.length > 265000000) {
    resp.body = ''
}
```
But it is suitable just in case you do not care about 1 page in thousands.

**Comment by Tjatse** [comment]
Appreciate. How about throw an Error when the body length is overflowing
