### ISSUE TITLE
multipart/form-data upload?

### ISSUE THREAD

**Issue by dexcell** [Tjatse/req-fast#2]
Hi @Tjatse 

I plan to ditch the `request` lib for all of my new projects, and i felt your `req-fast` could be the answer that i have been looking for (it's simple and to the point, and deserve more stars).

Today i have a problem uploading file to a site which uses REST API which use `POST` `multipart/form-data` as just like any HTML form do.

I know i can do it using `request` module, but i just wonder if it's possible with `req-fast`, since i don't want to require both `request` and `req-fast` as it's a module for similar task.

If you can write the code while not sacrifice any speed / lightness of `req-fast`, i think this should be at least included in `req-fast` as uploading file is a very common issue.

What do you think about this?

Thank you

**Comment by dexcell** [comment]
But if you think it's going to bloat the `req-fast`, separating them into another module e.g `req-fast-upload`, that can extend `req-fast` just like what `express` did to simplify their core is also another option.

So for those people who need the `multipart/form-data` can use this module.
Just a thought.

**Comment by Tjatse** [comment]
Hi @dexcell thanks for your advise, like what i said, `req-fast` is the *Fastest way to fetch the web content(HTML stream) from server*, I just spend times on how to crawl webs but not `post` things. I'm using [restler](https://github.com/danwrong/restler) to do the upload job, it's very powerful (more than `request`), maybe you can try it.

**Comment by dexcell** [comment]
Yeah i also thought about it, that's why i thought about separating the post `multipart/form-data` into another module in case you make one.
But thanks for your suggestion, i will try it.

**Comment by Tjatse** [comment]
Heh, there're too many excellent modules to do this, you can try `restler`, I think it is what you want.
