### ISSUE TITLE
Could not install req-fast

### ISSUE THREAD

**Issue by ndaidong** [Tjatse/req-fast#5]
Hi there,

I have an issue with req-fast here:

https://github.com/npm/npm/issues/11053

Could you help me resolve it?

Thanks,
Dong

**Comment by Tjatse** [comment]
Try `sudo npm install req-fast --production` again.

**Comment by ndaidong** [comment]
@Tjatse : thank you for your quick update. I've got it done.

Note that installing it with the command you given is okay, but there will be a permission error with "node_modules" folder. I had to entirely remove it and then run "npm install" again - without sudo. It works as before.
