### ISSUE TITLE
No post data

### ISSUE THREAD

**Issue by vinnygambiny** [Tjatse/req-fast#8]
When I send post data, the server receive nothing but if I send with method get, the data is there...

`req({
    url : 'http://www.com',
    method: 'POST',
    data: {
        nickname    : nickname
    },
    dataType: 'json'
},
function(error, response) {
    console.log(response);
});`

**Comment by Tjatse** [comment]
Hi, dude, thanks for your feedback.
Like what I said:
> This module is designed to be the fast, lightweight way to fetch the web content(HTML stream) from specific server. 

To be honest,  if you wanna post data to your server, try to use [request](https://github.com/request/request) instead of this one, and if you wanna crawl pages (like spider), try this instead of `request`

:)

**Comment by vinnygambiny** [comment]
I need to post data to server and receive data the fasted way. I need to send request like 3000 time in one hour

req-fast with GET or request with POST is the best way ?

**Comment by Tjatse** [comment]
Indeed!
Uses `GET` method and auto-decodes HTML content  - `req-fast`
Otherwise - `request`
